function res = S_minus(t, x)
	global alpha_;
	res = [x(2); ...
		-alpha_ - x(1) - sin(x(2)) - x(1) * sin(x(1)^3); ...
		x(4) * (1 + sin(x(1)^3) + 3.0 * x(1)^3 * cos(x(1)^3)); ...
		x(4) * cos(x(2)) - x(3) ];
end